<?php
require_once("incs-funcs.inc.php");

$crypt = new SedaCrypt();
$cms = getCMS();
$rsaKeys = $cms->get_option("seda_keys");

$msg="";
// Check if image file is a actual image or fake image
if(isset($_POST["submit"]) && ($_FILES["fileToUpload"]["size"]>0)) {
/*************/
	$expectedAnswer = $crypt->c2a($_POST['hashKey'],"",$rsaKeys['symmetric']);
	$keyValid = ($expectedAnswer == $_POST['ga']);
	if (!$keyValid && class_exists(NumberFormatter))
	{
		//what if user just used the wrong language?
		//if they have the NumberFormatter installed, translate encoding
		$fmt = numfmt_create('fa', NumberFormatter::DECIMAL);
		$givenAnswer = numfmt_parse($fmt,  $_POST['ga']);	
		$keyValid = ($expectedAnswer == $givenAnswer);
	}
/*************/
	$target_dir = "uploads/";
	$target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
	$uploadOk = 1;
	$imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);
	$check = getimagesize($_FILES["fileToUpload"]["tmp_name"]);
	if (!in_array($imageFileType, 
		array('png', 'gif', 'jpg','jpeg', 'ogg','mp3','mp4'))) 
	{
		$uploadOk = 0;
	}
	// Check if $uploadOk is set to 0 by an error
	if ($keyValid ==0 || $uploadOk == 0) {
	    $msg.="<span>".$lang["sorry_not_uploaded"].".</span>";
	// if everything is ok, try to upload file
	} else {
		$uploadedfile = $_FILES['fileToUpload'];
		$upload_overrides = array( 'test_form' => false );
		//WP handles escaping characters, etc. 
		$movefile = $cms->handle_upload( $uploadedfile, $upload_overrides );
		if ( $movefile && ((!isset( $movefile['error'])||$movefile['error']==0 )) ) {
		    //echo "File is valid, and was successfully uploaded.\n";
		    //var_dump( $movefile);
		    $file_array = array(
			    'name' => $uploadedfile["name"],
			    'type' =>$uploadedfile["type"], 
			    'tmp_name' => $movefile["file"], 
			    'error' => 0, 
			    'size' => $uploadedfile["size"]
			);
		    if ($uploadedfile["type"]=="image/jpeg")
		     {
	                    $img = new Imagick($movefile["file"]);
        	            $img->stripImage();
                	    $img->writeImage($movefile["file"]);
	                    $img->clear();
        	            $img->destroy();
		     }
		   //double check for XSS in case CMS misses it
		   //accepted filetypes are enforced by CMS, and configured in its config
		   $id=  $cms->media_sideload($file_array, 0, htmlspecialchars($_POST['fileTitle']));
		   if ( $cms->is_error($id) ) {
		    $msg=$lang['error'].":<br /><span dir=ltr>".$id."</span>";
		   }
		   else {	
		    //this URL will be S3 if configured, else a local URL on this server
		    $msg.=$lang['file_success']."&nbsp;<a href=\"".$cms->get_attachment_url($id)."\">".$lang['see_here']."</a>.\n";
		   }
		} else {
		    /**
		     * Error generated by _wp_handle_upload()
		     * In Drupal emulated but CMS classes
		     * @see _wp_handle_upload() in wp-admin/includes/file.php
		     */
		    $msg=$lang['error'].":<br /><span dir=ltr>".$movefile['error']."</span>";
	        }
	}
}
include("includes/mobile.inc.php");
?> 

